.TH "XY_bitmap" 3 "25 Dec 2008" "libcrtxy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XY_bitmap \- \fBXY_bitmap\fP - libcrtxy bitmap type.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <crtxy.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "SDL_Surface * \fBsurf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBXY_bitmap\fP - libcrtxy bitmap type. 
.SH "Field Documentation"
.PP 
.SS "SDL_Surface* \fBXY_bitmap::surf\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libcrtxy from the source code.
