.TH "Boolean type." 3 "2 Sep 2008" "libcrtxy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Boolean type. \- 
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBXY_bool\fP { \fBXY_FALSE\fP, \fBXY_TRUE\fP }"
.br
.RI "\fIBoolean type. \fP"
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBXY_bool\fP"
.PP
Boolean type. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIXY_FALSE \fP\fP
False. 
.TP
\fB\fIXY_TRUE \fP\fP
True. 

