.TH "libcrtxy boolean type" 3 "25 Dec 2008" "libcrtxy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcrtxy boolean type \- 
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBXY_bool\fP { \fBXY_FALSE\fP, \fBXY_TRUE\fP }"
.br
.RI "\fIXY_bool - libcrtxy boolean type. \fP"
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBXY_bool\fP"
.PP
XY_bool - libcrtxy boolean type. 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIXY_FALSE \fP\fP
False. 
.TP
\fB\fIXY_TRUE \fP\fP
True. 

