.TH "XY_line" 3 "25 Dec 2008" "libcrtxy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XY_line \- \fBXY_line\fP - libcrtxy structure representing a single line.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <crtxy.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXY_fixed\fP \fBx1\fP"
.br
.RI "\fIX coordinate of line starting point. \fP"
.ti -1c
.RI "\fBXY_fixed\fP \fBy1\fP"
.br
.RI "\fIY coordinate of line starting point. \fP"
.ti -1c
.RI "\fBXY_fixed\fP \fBx2\fP"
.br
.RI "\fIX coordinate of line end point. \fP"
.ti -1c
.RI "\fBXY_fixed\fP \fBy2\fP"
.br
.RI "\fIY coordinate of line end point. \fP"
.ti -1c
.RI "\fBXY_color\fP \fBcolor\fP"
.br
.RI "\fIColor of line. \fP"
.ti -1c
.RI "\fBXY_fixed\fP \fBthickness\fP"
.br
.RI "\fIThickness of line. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBXY_line\fP - libcrtxy structure representing a single line. 
.SH "Field Documentation"
.PP 
.SS "\fBXY_fixed\fP \fBXY_line::x1\fP"
.PP
X coordinate of line starting point. 
.PP
.SS "\fBXY_fixed\fP \fBXY_line::y1\fP"
.PP
Y coordinate of line starting point. 
.PP
.SS "\fBXY_fixed\fP \fBXY_line::x2\fP"
.PP
X coordinate of line end point. 
.PP
.SS "\fBXY_fixed\fP \fBXY_line::y2\fP"
.PP
Y coordinate of line end point. 
.PP
.SS "\fBXY_color\fP \fBXY_line::color\fP"
.PP
Color of line. 
.PP
.SS "\fBXY_fixed\fP \fBXY_line::thickness\fP"
.PP
Thickness of line. 
.PP
\fBTodo\fP
.RS 4
Implement thick lines 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libcrtxy from the source code.
