.TH "XY_lines" 3 "25 Dec 2008" "libcrtxy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XY_lines \- \fBXY_lines\fP - libcrtxy structure representing a group of lines.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <crtxy.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcount\fP"
.br
.RI "\fIHow many lines are currently in the group. \fP"
.ti -1c
.RI "int \fBmax\fP"
.br
.RI "\fIHow many lines the group can hold (used for memory allocation/reallocation). \fP"
.ti -1c
.RI "\fBXY_line\fP * \fBlines\fP"
.br
.RI "\fIThe lines. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBXY_lines\fP - libcrtxy structure representing a group of lines. 
.SH "Field Documentation"
.PP 
.SS "int \fBXY_lines::count\fP"
.PP
How many lines are currently in the group. 
.PP
.SS "int \fBXY_lines::max\fP"
.PP
How many lines the group can hold (used for memory allocation/reallocation). 
.PP
.SS "\fBXY_line\fP* \fBXY_lines::lines\fP"
.PP
The lines. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libcrtxy from the source code.
