.TH "libcrtxy bitmap positioning flags" 3 "25 Dec 2008" "libcrtxy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcrtxy bitmap positioning flags \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBXY_POS_TOP\fP   0x0"
.br
.RI "\fIPosition background at the top (default). \fP"
.ti -1c
.RI "#define \fBXY_POS_LEFT\fP   0x0"
.br
.RI "\fIPosition background on the left (default). \fP"
.ti -1c
.RI "#define \fBXY_POS_HCENTER\fP   0x1"
.br
.RI "\fIHorizontally center background. \fP"
.ti -1c
.RI "#define \fBXY_POS_VCENTER\fP   0x2"
.br
.RI "\fIVertically center background. \fP"
.ti -1c
.RI "#define \fBXY_POS_RIGHT\fP   0x4"
.br
.RI "\fIPosition background at the right. \fP"
.ti -1c
.RI "#define \fBXY_POS_BOTTOM\fP   0x8"
.br
.RI "\fIPosition background at the bottom. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define XY_POS_TOP   0x0"
.PP
Position background at the top (default). 
.PP
.SS "#define XY_POS_LEFT   0x0"
.PP
Position background on the left (default). 
.PP
.SS "#define XY_POS_HCENTER   0x1"
.PP
Horizontally center background. 
.PP
.SS "#define XY_POS_VCENTER   0x2"
.PP
Vertically center background. 
.PP
.SS "#define XY_POS_RIGHT   0x4"
.PP
Position background at the right. 
.PP
.SS "#define XY_POS_BOTTOM   0x8"
.PP
Position background at the bottom. 
.PP

